# Appartment-Hunter

### Imports de bibliothèques

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data/raw/kc_house_data.csv")
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

We find that the *date* column is an object type.
So in order to use it we'll need to turn it into a datetime type

In [5]:
df["date"]=pd.to_datetime(df["date"], errors='coerce')
df["date"].head()

0   2014-10-13
1   2014-12-09
2   2015-02-25
3   2014-12-09
4   2015-02-18
Name: date, dtype: datetime64[ns]

Actually, the date is between 2014 and 2015 so the impact of this column is very low. So we'll drop it.<br>
The id is useless in our case, we don't need to link each entry to a certain table, this is going to disturb our model.

In [6]:
df=df.drop("date", axis=1)
df=df.drop("id", axis=1)

In [7]:
df.duplicated().sum()
df[df.duplicated()]

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
3951,550000.0,4,1.75,2410,8447,2.0,0,3,4,8,2060,350,1936,1980,98074,47.6499,-122.088,2520,14789
4352,259950.0,2,2.00,1070,649,2.0,0,0,3,9,720,350,2008,0,98106,47.5213,-122.357,1070,928
14983,585000.0,3,2.50,2290,5089,2.0,0,0,3,9,2290,0,2001,0,98006,47.5443,-122.172,2290,7984
20054,555000.0,3,2.50,1940,3211,2.0,0,0,3,8,1940,0,2009,0,98027,47.5644,-122.093,1880,3078
20524,529500.0,3,2.25,1410,905,3.0,0,0,3,9,1410,0,2014,0,98116,47.5818,-122.402,1510,1352

0 duplicates and 0 non-null values

In [8]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [9]:
renovation_outlier = df[(df['yr_renovated'] != 0) & (df['yr_renovated'] < df['yr_built'])]
rooms_outlier = df[(df["bathrooms"] > df["bedrooms"] + 2)]

print(len(renovation_outlier),len(rooms_outlier))
rooms_outlier.head()
df.drop(index=rooms_outlier.index)

0 3

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,sqft_lot15,price_per_living_sqft,price_per_lot_sqft,sqm_living,sqm_lot,sqm_basement,sqm_living15,sqm_price_per_lot,sqm_price_per_living,sqm_lot15
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,...,5650,188.050847,39.274336,109.62554,524.901950,0.00000,124.49002,3.648704,17.470488,524.901950
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,...,7639,209.338521,74.288870,238.76071,672.803526,37.16120,157.00607,6.901659,19.448177,709.686017
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,...,8062,233.766234,18.000000,71.53531,929.030000,0.00000,252.69616,1.672254,21.717584,748.983986
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,...,5000,308.163265,120.800000,182.08988,464.515000,84.54173,126.34808,11.222682,28.629292,464.515000
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,...,7503,303.571429,63.118812,156.07704,750.656240,0.00000,167.22540,5.863927,28.202696,697.051209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,...,1509,235.294118,318.302387,142.14159,105.073293,0.00000,142.14159,29.571247,21.859529,140.190627
21609,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,...,7200,173.160173,68.811285,214.60593,540.045139,0.00000,170.01249,6.392775,16.087100,668.901600
21610,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,...,2007,394.216667,297.852593,94.76106,125.419050,0.00000,94.76106,27.671399,36.623911,186.456321
21611,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,...,1287,250.000000,167.504188,148.64480,221.852364,0.00000,130.99323,15.561642,23.225750,119.566161
21612,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,...,1357,318.627451,302.044610,94.76106,99.963628,0.00000,94.76106,28.060850,29.601446,126.069371

No houses have been renovated before the year date. So these columns seem ok to keep.

For more column treatment and values verification, we need to create new columns as : <br>
price_per_living_sqft = price / sqft_living
price_per_lot_sqft = price / sqft_lot

In [10]:
df["price_per_living_sqft"]=df["price"]/df['sqft_living']
df["price_per_lot_sqft"]=df["price"]/df['sqft_lot']
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price_per_living_sqft,price_per_lot_sqft
count,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,...,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,...,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652,264.156594,88.966710
std,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,...,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631,110.060793,94.055247
min,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000,87.588235,0.163119
25%,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,...,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000,182.291667,33.333333
50%,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,...,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000,244.644550,59.223301
75%,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,...,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000,318.322981,107.594937
max,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,...,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000,810.138889,2027.208539

We're going to stop being imperial and go to the metric system

In [14]:
df['sqm_living']=df['sqft_living']* 0.092903
df['sqm_lot']=df['sqft_lot']* 0.092903
df['sqm_basement']=df['sqft_basement']* 0.092903
df['sqm_living15']=df['sqft_living15']* 0.092903
df['sqm_price_per_lot']=df['price_per_lot_sqft']* 0.092903
df['sqm_price_per_living']=df['price_per_living_sqft']* 0.092903
df['sqm_lot15']=df['sqft_lot15']* 0.092903
df.drop(columns=['sqft_living','sqft_lot','sqft_basement','sqft_living15','price_per_lot_sqft','price_per_living_sqft','sqft_lot15'])

,price,bedrooms,bathrooms,floors,waterfront,view,condition,grade,sqft_above,yr_built,...,zipcode,lat,long,sqm_living,sqm_lot,sqm_basement,sqm_living15,sqm_price_per_lot,sqm_price_per_living,sqm_lot15
0,221900.0,3,1.00,1.0,0,0,3,7,1180,1955,...,98178,47.5112,-122.257,109.62554,524.901950,0.00000,124.49002,3.648704,17.470488,524.901950
1,538000.0,3,2.25,2.0,0,0,3,7,2170,1951,...,98125,47.7210,-122.319,238.76071,672.803526,37.16120,157.00607,6.901659,19.448177,709.686017
2,180000.0,2,1.00,1.0,0,0,3,6,770,1933,...,98028,47.7379,-122.233,71.53531,929.030000,0.00000,252.69616,1.672254,21.717584,748.983986
3,604000.0,4,3.00,1.0,0,0,5,7,1050,1965,...,98136,47.5208,-122.393,182.08988,464.515000,84.54173,126.34808,11.222682,28.629292,464.515000
4,510000.0,3,2.00,1.0,0,0,3,8,1680,1987,...,98074,47.6168,-122.045,156.07704,750.656240,0.00000,167.22540,5.863927,28.202696,697.051209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.0,3,2.50,3.0,0,0,3,8,1530,2009,...,98103,47.6993,-122.346,142.14159,105.073293,0.00000,142.14159,29.571247,21.859529,140.190627
21609,400000.0,4,2.50,2.0,0,0,3,8,2310,2014,...,98146,47.5107,-122.362,214.60593,540.045139,0.00000,170.01249,6.392775,16.087100,668.901600
21610,402101.0,2,0.75,2.0,0,0,3,7,1020,2009,...,98144,47.5944,-122.299,94.76106,125.419050,0.00000,94.76106,27.671399,36.623911,186.456321
21611,400000.0,3,2.50,2.0,0,0,3,8,1600,2004,...,98027,47.5345,-122.069,148.64480,221.852364,0.00000,130.99323,15.561642,23.225750,119.566161
21612,325000.0,2,0.75,2.0,0,0,3,7,1020,2008,...,98144,47.5941,-122.299,94.76106,99.963628,0.00000,94.76106,28.060850,29.601446,126.069371